In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

# Data Preprocessing

In [3]:
movies=movies.merge(credits,on='title')

In [4]:
movies.shape

(4809, 23)

In [5]:
credits.shape

(4803, 4)

In [6]:
#genres
#id
# keywords
# title
# overview
#cast
#crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [7]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()#for searching missing data

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

np.int64(0)

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
# we have to change ['Action','Adventure','Fantasy','Science Fiction'] format

In [13]:
import ast

def convert(text):
    L = []

    # convert string to list of dictionaries
    if isinstance(text, str):
        text = ast.literal_eval(text)

    for i in text:
        # handle both dicts and strings
        if isinstance(i, dict):
            L.append(i['name'])
        else:
            L.append(i)

    return L

# Apply the corrected function
movies['genres'] = movies['genres'].apply(convert)  # applying corrected function

In [14]:
movies.dropna(inplace=True)

In [15]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies['keywords']=movies['keywords'].apply(convert)

In [17]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [18]:

def convert3(text):
    L = []
    counter = 0

    # convert string to list if needed
    if isinstance(text, str):
        text = ast.literal_eval(text)

    for i in text:
        if counter < 3:
            if isinstance(i, dict):
                L.append(i['name'])
            else:
                L.append(i)
        counter += 1

    return L

# Apply the function
movies['cast'] = movies['cast'].apply(convert3)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [20]:
def fetch_director(text):
    L = []

    # convert string to list if needed
    if isinstance(text, str):
        text = ast.literal_eval(text)

    for i in text:
        if isinstance(i, dict):
            if i.get('job') == 'Director':
                L.append(i.get('name'))

    return L

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [22]:
movies['crew'][0]

['James Cameron']

In [23]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [24]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
# we have to remove sppaces from names because model model can get confuse like between sam mendes and sam worthington we have to do sammendes and samworthington

In [27]:
movies['genres']=movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [29]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [30]:
new=movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [31]:
#we drop thiis columns and add tags named column which contain all of this instead of seprate columns and make one new dataframe

In [32]:
new_df=movies[['movie_id','title','tags',]]

In [33]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\ASUS\AppData\Local\Temp\ipykernel_31248\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [35]:
import nltk

In [36]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
#we join all comma seperated values after concatation into space sepreted paragraphs

In [38]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [39]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_31248\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

# vectorization

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [43]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [44]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [45]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [46]:
#we will apply steming to covert the similiar words into one
# for ex[love,loving,love]
# output: [love,love,love]

In [47]:
def stem(text):#to  convert similiar words into single one using stemming
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [48]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_31248\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [49]:
ps.stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [50]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
similarity = cosine_similarity(vectors)

In [53]:
similarity#har movie vector ka har movie vector ke sath kaa angle(similarity)

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]], shape=(4806, 4806))

In [54]:
list(enumerate(similarity[0]))# isme har movie ka har movie ke sath ka distance properly diya hai

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.08964214570007951)),
 (2, np.float64(0.060717674071891624)),
 (3, np.float64(0.03984095364447979)),
 (4, np.float64(0.18257418583505533)),
 (5, np.float64(0.1183452670827877)),
 (6, np.float64(0.023218173010628604)),
 (7, np.float64(0.1763834207376394)),
 (8, np.float64(0.06388765649999398)),
 (9, np.float64(0.07733088933397005)),
 (10, np.float64(0.11769797726729993)),
 (11, np.float64(0.081199794294115)),
 (12, np.float64(0.09583148474999097)),
 (13, np.float64(0.04733810683311508)),
 (14, np.float64(0.11428571428571427)),
 (15, np.float64(0.05096471914376255)),
 (16, np.float64(0.08226127456606226)),
 (17, np.float64(0.15026857675938213)),
 (18, np.float64(0.11194341570991125)),
 (19, np.float64(0.08728715609439693)),
 (20, np.float64(0.058167505074711086)),
 (21, np.float64(0.09416472308615166)),
 (22, np.float64(0.06900655593423542)),
 (23, np.float64(0.09759000729485331)),
 (24, np.float64(0.0563436169819011)),
 (25, np.float64(0.03877833671647406)),
 (26, np.float64(0.17142857142857143)),
 (27, np.float64(0.18752289237539818)),
 (28, np.float64(0.12555296411486888)),
 (29, np.float64(0.07100716024967262)),
 (30, np.float64(0.07319250547113999)),
 (31, np.float64(0.15971914124998496)),
 (32, np.float64(0.09116846116771035)),
 (33, np.float64(0.1057361065275362)),
 (34, np.float64(0.0)),
 (35, np.float64(0.11065666703449761)),
 (36, np.float64(0.19194297398747862)),
 (37, np.float64(0.08451542547285165)),
 (38, np.float64(0.0628970902033151)),
 (39, np.float64(0.08827348295047495)),
 (40, np.float64(0.0563436169819011)),
 (41, np.float64(0.14638501094227999)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09759000729485333)),
 (44, np.float64(0.040996003084539386)),
 (45, np.float64(0.09116846116771037)),
 (46, np.float64(0.1765469659009499)),
 (47, np.float64(0.2164218276749025)),
 (48, np.float64(0.06776309271789384)),
 (49, np.float64(0.06388765649999398)),
 (50, np.float64(0.12344267996967351)),
 (51, np.float64(0.08586775814821836)),
 (52, np.float64(0.1449427589131121)),
 (53, np.float64(0.04931136727215379)),
 (54, np.float64(0.035245368842512066)),
 (55, np.float64(0.07655590023509526)),
 (56, np.float64(0.14414999403128942)),
 (57, np.float64(0.028988551782622416)),
 (58, np.float64(0.04733810683311508)),
 (59, np.float64(0.08024108542850393)),
 (60, np.float64(0.028988551782622416)),
 (61, np.float64(0.2162249910469341)),
 (62, np.float64(0.08199200616907877)),
 (63, np.float64(0.09200874124564722)),
 (64, np.float64(0.03138824102871722)),
 (65, np.float64(0.020965696734438367)),
 (66, np.float64(0.02492223931396134)),
 (67, np.float64(0.17928429140015903)),
 (68, np.float64(0.13259870882635919)),
 (69, np.float64(0.0520265981714472)),
 (70, np.float64(0.081199794294115)),
 (71, np.float64(0.08226127456606226)),
 (72, np.float64(0.12344267996967351)),
 (73, np.float64(0.03779644730092272)),
 (74, np.float64(0.22677868380553634)),
 (75, np.float64(0.09258200997725513)),
 (76, np.float64(0.07824607964359516)),
 (77, np.float64(0.014824986333222025)),
 (78, np.float64(0.05345224838248488)),
 (79, np.float64(0.07824607964359516)),
 (80, np.float64(0.03450327796711771)),
 (81, np.float64(0.11710800875382396)),
 (82, np.float64(0.08336550215650926)),
 (83, np.float64(0.22190115272469205)),
 (84, np.float64(0.1456438162508838)),
 (85, np.float64(0.10631548679075009)),
 (86, np.float64(0.08827348295047495)),
 (87, np.float64(0.11595420713048966)),
 (88, np.float64(0.09107651110783743)),
 (89, np.float64(0.06146576398025575)),
 (90, np.float64(0.06506000486323554)),
 (91, np.float64(0.15971914124998496)),
 (92, np.float64(0.07100716024967262)),
 (93, np.float64(0.05039526306789696)),
 (94, np.float64(0.16574838603294897)),
 (95, np.float64(0.1246111965698067)),
 (96, np.float64(0.08964214570007951)),
 (97, np.float64(0.07476671794188401)),
 (98, np.float64(0.08827348295047495)),
 (99, np.float64(0.029880715233359837)),
 (100, np.float64(0.07377111135633174)),
 (101, np.float64(0.08827348295047495)),
 (102, np.float64(0.11194341570991125)),
 (103, np.float64(0.08877935232369503)),
 (104, np.float64(0.05884898863364997)),
 (105, np.float64(0.10811249552346706)),
 (106, np.float64(0.0447773662839645)),
 (107, np.float64(0.09200874124564722)),
 (108, np.float64(0.16903085094570328)),
 (109, np.float64(0.07968190728895957)),
 (110, np.float64(0.024397501823713332)),
 (111, np.float64(0.15430334996209188)),
 (112, np.float64(0.09107651110783743)),
 (113, np.float64(0.052796367734845466)),
 (114, np.float64(0.052796367734845466)),
 (115, np.float64(0.05413319619607667)),
 (116, np.float64(0.057142857142857134)),
 (117, np.float64(0.060717674071891624)),
 (118, np.float64(0.017622684421256033)),
 (119, np.float64(0.048795003647426664)),
 (120, np.float64(0.0)),
 (121, np.float64(0.09107651110783743)),
 (122, np.float64(0.09583148474999097)),
 (123, np.float64(0.12198750911856666)),
 (124, np.float64(0.06837634587578277)),
 (125, np.float64(0.07985957062499248)),
 (126, np.float64(0.11595420713048966)),
 (127, np.float64(0.13572417850765922)),
 (128, np.float64(0.0)),
 (129, np.float64(0.10559273546969093)),
 (130, np.float64(0.03194382824999699)),
 (131, np.float64(0.1126872339638022)),
 (132, np.float64(0.045584230583855176)),
 (133, np.float64(0.033149677206589796)),
 (134, np.float64(0.13522468075656266)),
 (135, np.float64(0.0)),
 (136, np.float64(0.025482359571881275)),
 (137, np.float64(0.034324965259398446)),
 (138, np.float64(0.08226127456606226)),
 (139, np.float64(0.10821091383745125)),
 (140, np.float64(0.05096471914376255)),
 (141, np.float64(0.11338934190276816)),
 (142, np.float64(0.09759000729485331)),
 (143, np.float64(0.06965451903188581)),
 (144, np.float64(0.055577001437672836)),
 (145, np.float64(0.02258769757263128)),
 (146, np.float64(0.017251638983558856)),
 (147, np.float64(0.06277648205743444)),
 (148, np.float64(0.1057361065275362)),
 (149, np.float64(0.173137462139922)),
 (150, np.float64(0.18869127060994534)),
 (151, np.float64(0.20498001542269692)),
 (152, np.float64(0.06388765649999398)),
 (153, np.float64(0.086568731069961)),
 (154, np.float64(0.033149677206589796)),
 (155, np.float64(0.0)),
 (156, np.float64(0.06658451424277127)),
 (157, np.float64(0.1057361065275362)),
 (158, np.float64(0.15289415743128765)),
 (159, np.float64(0.06761234037828133)),
 (160, np.float64(0.09694584179118515)),
 (161, np.float64(0.035245368842512066)),
 (162, np.float64(0.03688555567816587)),
 (163, np.float64(0.05413319619607667)),
 (164, np.float64(0.09416472308615166)),
 (165, np.float64(0.04984447862792268)),
 (166, np.float64(0.11952286093343935)),
 (167, np.float64(0.06900655593423542)),
 (168, np.float64(0.16035674514745463)),
 (169, np.float64(0.11952286093343936)),
 (170, np.float64(0.09200874124564722)),
 (171, np.float64(0.029424494316824985)),
 (172, np.float64(0.15118578920369088)),
 (173, np.float64(0.024397501823713332)),
 (174, np.float64(0.11115400287534567)),
 (175, np.float64(0.0515539262226467)),
 (176, np.float64(0.030860669992418377)),
 (177, np.float64(0.0)),
 (178, np.float64(0.02577696311132335)),
 (179, np.float64(0.07559289460184544)),
 (180, np.float64(0.023904572186687872)),
 (181, np.float64(0.02344036154692477)),
 (182, np.float64(0.10690449676496976)),
 (183, np.float64(0.07466533929465573)),
 (184, np.float64(0.18257418583505533)),
 (185, np.float64(0.055577001437672836)),
 (186, np.float64(0.040697846377823976)),
 (187, np.float64(0.14085904245475275)),
 (188, np.float64(0.02258769757263128)),
 (189, np.float64(0.08199200616907877)),
 (190, np.float64(0.08386278693775347)),
 (191, np.float64(0.0515539262226467)),
 (192, np.float64(0.0)),
 (193, np.float64(0.08728715609439693)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06506000486323554)),
 (196, np.float64(0.05884898863364997)),
 (197, np.float64(0.048795003647426664)),
 (198, np.float64(0.059761430466719674)),
 (199, np.float64(0.11720180773462387)),
 (200, np.float64(0.07755667343294811)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03450327796711771)),
 (203, np.float64(0.08827348295047495)),
 (204, np.float64(0.02672612419124244)),
 (205, np.float64(0.08199200616907877)),
 (206, np.float64(0.09694584179118515)),
 (207, np.float64(0.0857142857142857)),
 (208, np.float64(0.1690308509457033)),
 (209, np.float64(0.03877833671647406)),
 (210, np.float64(0.05484084971070818)),
 (211, np.float64(0.02742042485535409)),
 (212, np.float64(0.07644707871564382)),
 (213, np.float64(0.0654653670707977)),
 (214, np.float64(0.028988551782622416)),
 (215, np.float64(0.07396705090823068)),
 (216, np.float64(0.06506000486323554)),
 (217, np.float64(0.04643634602125721)),
 (218, np.float64(0.042257712736425826)),
 (219, np.float64(0.06629935441317959)),
 (220, np.float64(0.18832944617230335)),
 (221, np.float64(0.024655683636076894)),
 (222, np.float64(0.09035079029052512)),
 (223, np.float64(0.08336550215650926)),
 (224, np.float64(0.06338656910463875)),
 (225, np.float64(0.052164053095730106)),
 (226, np.float64(0.029880715233359837)),
 (227, np.float64(0.09258200997725513)),
 (228, np.float64(0.12598815766974242)),
 (229, np.float64(0.07913425882489307)),
 (230, np.float64(0.08877935232369503)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11952286093343935)),
 (233, np.float64(0.10811249552346706)),
 (234, np.float64(0.06776309271789384)),
 (235, np.float64(0.060717674071891624)),
 (236, np.float64(0.09759000729485331)),
 (237, np.float64(0.07049073768502413)),
 (238, np.float64(0.12777531299998796)),
 (239, np.float64(0.1109741904046188)),
 (240, np.float64(0.05096471914376255)),
 (241, np.float64(0.08964214570007951)),
 (242, np.float64(0.09416472308615166)),
 (243, np.float64(0.09968895725584535)),
 (244, np.float64(0.06277648205743444)),
 (245, np.float64(0.09107651110783743)),
 (246, np.float64(0.06601782722034923)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04733810683311508)),
 (249, np.float64(0.14414999403128942)),
 (250, np.float64(0.0)),
 (251, np.float64(0.042257712736425826)),
 (252, np.float64(0.022792115291927588)),
 (253, np.float64(0.06601782722034923)),
 (254, np.float64(0.08336550215650926)),
 (255, np.float64(0.0)),
 (256, np.float64(0.08199200616907877)),
 (257, np.float64(0.08696565534786725)),
 (258, np.float64(0.02344036154692477)),
 (259, np.float64(0.06388765649999398)),
 (260, np.float64(0.25110592822973776)),
 (261, np.float64(0.025482359571881275)),
 (262, np.float64(0.07476671794188401)),
 (263, np.float64(0.1057361065275362)),
 (264, np.float64(0.0)),
 (265, np.float64(0.029424494316824985)),
 (266, np.float64(0.11115400287534567)),
 (267, np.float64(0.07559289460184544)),
 (268, np.float64(0.02742042485535409)),
 (269, np.float64(0.033149677206589796)),
 (270, np.float64(0.1031078524452934)),
 (271, np.float64(0.0791945516022682)),
 (272, np.float64(0.030860669992418377)),
 (273, np.float64(0.024655683636076894)),
 (274, np.float64(0.08058229640253803)),
 (275, np.float64(0.12555296411486888)),
 (276, np.float64(0.06761234037828133)),
 (277, np.float64(0.06601782722034923)),
 (278, np.float64(0.1031078524452934)),
 (279, np.float64(0.1031078524452934)),
 (280, np.float64(0.0)),
 (281, np.float64(0.07319250547113999)),
 (282, np.float64(0.030860669992418377)),
 (283, np.float64(0.0)),
 (284, np.float64(0.020203050891044214)),
 (285, np.float64(0.022792115291927588)),
 (286, np.float64(0.02258769757263128)),
 (287, np.float64(0.02742042485535409)),
 (288, np.float64(0.0)),
 (289, np.float64(0.05039526306789696)),
 (290, np.float64(0.06761234037828133)),
 (291, np.float64(0.0563436169819011)),
 (292, np.float64(0.10141851056742199)),
 (293, np.float64(0.03194382824999699)),
 (294, np.float64(0.11952286093343935)),
 (295, np.float64(0.10968169942141635)),
 (296, np.float64(0.040120542714251965)),
 (297, np.float64(0.04829452884162951)),
 (298, np.float64(0.0)),
 (299, np.float64(0.04161251892882394)),
 (300, np.float64(0.18708286933869708)),
 (301, np.float64(0.18182745801939793)),
 (302, np.float64(0.060717674071891624)),
 (303, np.float64(0.028988551782622416)),
 (304, np.float64(0.07207499701564471)),
 (305, np.float64(0.1932024558334913)),
 (306, np.float64(0.09416472308615166)),
 (307, np.float64(0.10460520656316098)),
 (308, np.float64(0.07049073768502413)),
 (309, np.float64(0.06629935441317959)),
 (310, np.float64(0.036037498507822355)),
 (311, np.float64(0.1564921592871903)),
 (312, np.float64(0.10968169942141635)),
 (313, np.float64(0.07968190728895957)),
 (314, np.float64(0.0)),
 (315, np.float64(0.09107651110783743)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.07207499701564471)),
 (320, np.float64(0.033806170189140665)),
 (321, np.float64(0.0)),
 (322, np.float64(0.22230800575069137)),
 (323, np.float64(0.033149677206589796)),
 (324, np.float64(0.026398183867422733)),
 (325, np.float64(0.11065666703449761)),
 (326, np.float64(0.05884898863364997)),
 (327, np.float64(0.028988551782622416)),
 (328, np.float64(0.0)),
 (329, np.float64(0.08336550215650926)),
 (330, np.float64(0.1126872339638022)),
 (331, np.float64(0.04984447862792268)),
 (332, np.float64(0.14285714285714285)),
 (333, np.float64(0.030860669992418377)),
 (334, np.float64(0.10690449676496976)),
 (335, np.float64(0.0563436169819011)),
 (336, np.float64(0.07377111135633174)),
 (337, np.float64(0.024147264420814756)),
 (338, np.float64(0.0)),
 (339, np.float64(0.057142857142857134)),
 (340, np.float64(0.052164053095730106)),
 (341, np.float64(0.061721339984836754)),
 (342, np.float64(0.1366260102127946)),
 (343, np.float64(0.022792115291927588)),
 (344, np.float64(0.03138824102871722)),
 (345, np.float64(0.02366905341655754)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06761234037828133)),
 (349, np.float64(0.09258200997725513)),
 (350, np.float64(0.05484084971070818)),
 (351, np.float64(0.0)),
 (352, np.float64(0.029424494316824985)),
 (353, np.float64(0.023904572186687872)),
 (354, np.float64(0.0)),
 (355, np.float64(0.040120542714251965)),
 (356, np.float64(0.09258200997725513)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06629935441317959)),
 (359, np.float64(0.03450327796711771)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0563436169819011)),
 (362, np.float64(0.09759000729485331)),
 (363, np.float64(0.09116846116771037)),
 (364, np.float64(0.026082026547865053)),
 (365, np.float64(0.081199794294115)),
 (366, np.float64(0.059761430466719674)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13522468075656266)),
 (369, np.float64(0.09258200997725513)),
 (370, np.float64(0.0563436169819011)),
 (371, np.float64(0.1031078524452934)),
 (372, np.float64(0.05345224838248488)),
 (373, np.float64(0.18018749253911176)),
 (374, np.float64(0.04438967616184752)),
 (375, np.float64(0.0432843655349805)),
 (376, np.float64(0.048795003647426664)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05345224838248487)),
 (380, np.float64(0.02817180849095055)),
 (381, np.float64(0.09035079029052512)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0515539262226467)),
 (384, np.float64(0.03253000243161777)),
 (385, np.float64(0.0)),
 (386, np.float64(0.024147264420814756)),
 (387, np.float64(0.02742042485535409)),
 (388, np.float64(0.0)),
 (389, np.float64(0.10141851056742199)),
 (390, np.float64(0.02817180849095055)),
 (391, np.float64(0.061494004626809075)),
 (392, np.float64(0.03138824102871722)),
 (393, np.float64(0.0)),
 (394, np.float64(0.026082026547865053)),
 (395, np.float64(0.057142857142857134)),
 (396, np.float64(0.02366905341655754)),
 (397, np.float64(0.055577001437672836)),
 (398, np.float64(0.0)),
 (399, np.float64(0.02577696311132335)),
 (400, np.float64(0.10350983390135314)),
 (401, np.float64(0.03194382824999699)),
 (402, np.float64(0.061721339984836754)),
 (403, np.float64(0.11002971203391539)),
 (404, np.float64(0.06761234037828133)),
 (405, np.float64(0.030860669992418377)),
 (406, np.float64(0.021821789023599235)),
 (407, np.float64(0.026082026547865053)),
 (408, np.float64(0.035245368842512066)),
 (409, np.float64(0.0)),
 (410, np.float64(0.10079052613579392)),
 (411, np.float64(0.05884898863364997)),
 (412, np.float64(0.1019294382875251)),
 (413, np.float64(0.1389425035941821)),
 (414, np.float64(0.033149677206589796)),
 (415, np.float64(0.07126966450997983)),
 (416, np.float64(0.0563436169819011)),
 (417, np.float64(0.033806170189140665)),
 (418, np.float64(0.03779644730092272)),
 (419, np.float64(0.07644707871564382)),
 (420, np.float64(0.12888481555661674)),
 (421, np.float64(0.0)),
 (422, np.float64(0.14754222271266348)),
 (423, np.float64(0.052164053095730106)),
 (424, np.float64(0.04040610178208843)),
 (425, np.float64(0.07100716024967262)),
 (426, np.float64(0.06195121541733006)),
 (427, np.float64(0.029424494316824985)),
 (428, np.float64(0.0593506941186698)),
 (429, np.float64(0.0)),
 (430, np.float64(0.052796367734845466)),
 (431, np.float64(0.02577696311132335)),
 (432, np.float64(0.12598815766974242)),
 (433, np.float64(0.033149677206589796)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03984095364447979)),
 (436, np.float64(0.0)),
 (437, np.float64(0.028988551782622416)),
 (438, np.float64(0.028571428571428567)),
 (439, np.float64(0.030860669992418377)),
 (440, np.float64(0.028571428571428567)),
 (441, np.float64(0.030358837035945812)),
 (442, np.float64(0.048795003647426664)),
 (443, np.float64(0.05884898863364997)),
 (444, np.float64(0.0)),
 (445, np.float64(0.028571428571428567)),
 (446, np.float64(0.02577696311132335)),
 (447, np.float64(0.023904572186687872)),
 (448, np.float64(0.026082026547865053)),
 (449, np.float64(0.05797710356524483)),
 (450, np.float64(0.026398183867422733)),
 (451, np.float64(0.026398183867422733)),
 (452, np.float64(0.03194382824999699)),
 (453, np.float64(0.02672612419124244)),
 (454, np.float64(0.12327841818038447)),
 (455, np.float64(0.024655683636076894)),
 (456, np.float64(0.07032108464077431)),
 (457, np.float64(0.08696565534786725)),
 (458, np.float64(0.04733810683311508)),
 (459, np.float64(0.036037498507822355)),
 (460, np.float64(0.028571428571428567)),
 (461, np.float64(0.1938916835823703)),
 (462, np.float64(0.0)),
 (463, np.float64(0.035245368842512066)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.2114722130550724)),
 (467, np.float64(0.09116846116771037)),
 (468, np.float64(0.030358837035945812)),
 (469, np.float64(0.07032108464077431)),
 (470, np.float64(0.04931136727215379)),
 (471, np.float64(0.08336550215650926)),
 (472, np.float64(0.08451542547285165)),
 (473, np.float64(0.1019294382875251)),
 (474, np.float64(0.0)),
 (475, np.float64(0.06837634587578277)),
 (476, np.float64(0.10811249552346706)),
 (477, np.float64(0.0)),
 (478, np.float64(0.03984095364447979)),
 (479, np.float64(0.09508728264112047)),
 (480, np.float64(0.052164053095730106)),
 (481, np.float64(0.0)),
 (482, np.float64(0.030358837035945812)),
 (483, np.float64(0.1301200097264711)),
 (484, np.float64(0.03450327796711771)),
 (485, np.float64(0.0563436169819011)),
 (486, np.float64(0.05855400437691198)),
 (487, np.float64(0.14098147537004826)),
 (488, np.float64(0.07606982611289638)),
 (489, np.float64(0.0)),
 (490, np.float64(0.15118578920369088)),
 (491, np.float64(0.09116846116771037)),
 (492, np.float64(0.06277648205743444)),
 (493, np.float64(0.01951800145897066)),
 (494, np.float64(0.0)),
 (495, np.float64(0.2162249910469341)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.07207499701564471)),
 (499, np.float64(0.0)),
 (500, np.float64(0.028571428571428567)),
 (501, np.float64(0.0880237696271323)),
 (502, np.float64(0.1546617786679401)),
 (503, np.float64(0.08336550215650926)),
 (504, np.float64(0.0)),
 (505, np.float64(0.14754222271266348)),
 (506, np.float64(0.03688555567816587)),
 (507, np.float64(0.24846467329894412)),
 (508, np.float64(0.11595420713048966)),
 (509, np.float64(0.02577696311132335)),
 (510, np.float64(0.10559273546969093)),
 (511, np.float64(0.09583148474999097)),

In [55]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]#lambda function shows that we have to do sortingbase on second number in each array of list which is a distance and with the help of [1:6] we extract top 5 movies havig closest distance

[(539, np.float64(0.26089696604360174)),
 (1192, np.float64(0.2581988897471611)),
 (260, np.float64(0.25110592822973776)),
 (1214, np.float64(0.24944382578492943)),
 (507, np.float64(0.24846467329894412))]

In [56]:
similarity[0]

array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
       0.        ], shape=(4806,))

# main function

In [57]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]#index of each movie in dataframe
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]#lambda function shows that we have to do sortingbase on second number in each array of list which is a distance and with the help of [1:6] we extract top 5 movies havig closest distance
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [58]:
new_df[new_df['title']=='Batman'].index[0]#index of each movie in dataframe

np.int64(1360)

In [59]:
recommend('Titanic')

Captain Phillips
The Notebook
In the Heart of the Sea
Ghost Ship
Poseidon

In [60]:
import pickle

In [61]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [62]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [64]:
pickle.dump(similarity,open('similarity.pkl','wb'))